"""option chain snapshots

Revision ID: 997e5e90aae3
Revises: a41fb8d7afe6
Created: 2026-08-04 15:44:41.500022+00:00

Checklist before merging:
  - Is this migration safe to run while the previous release is still serving?
    (no dropped columns still referenced, no blocking table rewrites)
  - Are new indexes created CONCURRENTLY on large tables?
  - Does downgrade() actually reverse upgrade(), or is it deliberately absent?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "997e5e90aae3"
down_revision: str | None = "a41fb8d7afe6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option_chain_snapshots",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiry", sa.String(length=10), nullable=True),
        sa.Column("spot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("future_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("atm_strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_call_oi", sa.BigInteger(), nullable=True),
        sa.Column("total_put_oi", sa.BigInteger(), nullable=True),
        sa.Column("pcr_oi", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("max_pain_strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source in ('live', 'mock')", name=op.f("ck_option_chain_snapshots_source_known")
        ),
        sa.CheckConstraint("spot > 0", name=op.f("ck_option_chain_snapshots_spot_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_chain_snapshots")),
    )
    op.create_index(
        "ix_option_chain_snapshots_lookup",
        "option_chain_snapshots",
        ["symbol", "session_date", "captured_at"],
        unique=False,
    )
    op.create_table(
        "option_chain_rows",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("option_type", sa.String(length=2), nullable=False),
        sa.Column("oi", sa.BigInteger(), nullable=False),
        sa.Column("oi_change", sa.BigInteger(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("ltp", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("iv", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("delta", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "option_type in ('CE', 'PE')", name=op.f("ck_option_chain_rows_option_type_known")
        ),
        sa.CheckConstraint("strike > 0", name=op.f("ck_option_chain_rows_strike_positive")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["option_chain_snapshots.id"],
            name=op.f("fk_option_chain_rows_snapshot_id_option_chain_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_chain_rows")),
    )
    op.create_index(
        "ix_option_chain_rows_snapshot",
        "option_chain_rows",
        ["snapshot_id", "option_type", "strike"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_option_chain_rows_snapshot", table_name="option_chain_rows")
    op.drop_table("option_chain_rows")
    op.drop_index("ix_option_chain_snapshots_lookup", table_name="option_chain_snapshots")
    op.drop_table("option_chain_snapshots")
    # ### end Alembic commands ###
