"""futures board snapshots

Revision ID: b2e21d34159e
Revises: 66ee91d6d8f0
Created: 2026-09-21 08:42:04.414337+00:00

Checklist before merging:
  - Is this migration safe to run while the previous release is still serving?
    (no dropped columns still referenced, no blocking table rewrites)
  - Are new indexes created CONCURRENTLY on large tables?
  - Does downgrade() actually reverse upgrade(), or is it deliberately absent?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b2e21d34159e"
down_revision: str | None = "66ee91d6d8f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "futures_board_snapshots",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("expiry", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source in ('live', 'mock')", name=op.f("ck_futures_board_snapshots_source_known")
        ),
        sa.CheckConstraint(
            "open_interest is null or open_interest >= 0",
            name=op.f("ck_futures_board_snapshots_open_interest_not_negative"),
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_futures_board_snapshots_price_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_futures_board_snapshots")),
        sa.UniqueConstraint("symbol", "captured_at", name="futures_board_snapshots_symbol_instant"),
    )
    op.create_index(
        "ix_futures_board_snapshots_lookup",
        "futures_board_snapshots",
        ["symbol", "session_date", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_futures_board_snapshots_lookup", table_name="futures_board_snapshots")
    op.drop_table("futures_board_snapshots")
    # ### end Alembic commands ###
