import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import ts from 'typescript-eslint';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node }
    }
  },
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: { parser: ts.parser }
    }
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' }
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }]
    }
  },
  {
    // SvelteKit's ambient declarations are intentionally empty until a feature
    // needs them; that is the documented shape, not an oversight.
    // `import()` types are required here too: a top-level import would turn
    // this ambient file into a module and remove the global App namespace.
    files: ['src/app.d.ts'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/consistent-type-imports': 'off'
    }
  },
  {
    // Wrapper components forward arbitrary DOM attributes through a rest prop.
    // The compiler warns that this prevents custom-element prop inference —
    // irrelevant here, since nothing is compiled to a custom element (see the
    // matching warningFilter in svelte.config.js).
    files: ['src/lib/shared/ui/*.svelte'],
    rules: { 'svelte/valid-compile': ['error', { ignoreWarnings: true }] }
  },
  {
    // Generated by orval from contracts/openapi — never hand-edited.
    ignores: [
      'build/',
      '.svelte-kit/',
      'node_modules/',
      'src/lib/shared/api/generated/',
      'playwright-report/',
      'test-results/'
    ]
  }
);
