import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import ts from 'typescript-eslint';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        ecmaFeatures: { jsx: true }
      }
    }
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      // Svelte's `$effect` tracked its own dependencies. `useEffect` does not,
      // and a wrong dependency array is the failure mode this migration is most
      // exposed to — so this is an error, not the default warning.
      'react-hooks/exhaustive-deps': 'error'
    }
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' }
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }]
    }
  },
  prettier,
  {
    // Generated by orval from contracts/openapi — never hand-edited. `.react-router`
    // is React Router's generated route-type output.
    ignores: [
      'build/',
      '.react-router/',
      'node_modules/',
      'app/lib/shared/api/generated/',
      'playwright-report/',
      'test-results/',
      'coverage/'
    ]
  }
);
