"""Alembic environment.

The database URL comes from application settings, never from alembic.ini, so
migrations and the running application can never disagree about which database
they are pointed at.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from marketcompass.bootstrap.settings import get_settings
from marketcompass.infrastructure.persistence.postgresql.metadata import target_metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
config.set_main_option("sqlalchemy.url", str(settings.database.url))

metadata = target_metadata()


def _include_object(_object, name: str, type_: str, _reflected, _compare_to) -> bool:  # type: ignore[no-untyped-def]
    """Keep infrastructure tables out of autogenerated migrations."""
    return not (type_ == "table" and name == "alembic_version")


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    context.configure(
        connection=connection,
        url=url,
        target_metadata=metadata,
        include_object=_include_object,
        # Without these, a column type or server-default change is silently
        # omitted from the generated migration.
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        transaction_per_migration=True,
        literal_binds=url is not None,
        dialect_opts={"paramstyle": "named"} if url is not None else {},
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of executing it (``alembic upgrade --sql``)."""
    _configure(url=str(settings.database.url))
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
