"""broker connections

Revision ID: a41fb8d7afe6
Revises: e9d1717bc917
Created: 2026-08-01 18:40:45.541417+00:00

Checklist before merging:
  - Is this migration safe to run while the previous release is still serving?
    (no dropped columns still referenced, no blocking table rewrites)
  - Are new indexes created CONCURRENTLY on large tables?
  - Does downgrade() actually reverse upgrade(), or is it deliberately absent?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a41fb8d7afe6"
down_revision: str | None = "e9d1717bc917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_connections",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=True),
        sa.Column("app_secret_enc", sa.Text(), nullable=True),
        sa.Column("access_token_enc", sa.Text(), nullable=True),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("broker in ('fyers')", name=op.f("ck_broker_connections_broker_known")),
        sa.CheckConstraint(
            "status <> 'active' or access_token_enc is not null",
            name=op.f("ck_broker_connections_active_requires_token"),
        ),
        sa.CheckConstraint(
            "status in ('pending', 'active', 'expired', 'revoked')",
            name=op.f("ck_broker_connections_status_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_connections")),
    )
    op.create_index(
        "ix_broker_connections_tenant_id", "broker_connections", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_broker_connections_active",
        "broker_connections",
        ["tenant_id", "broker"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_broker_connections_active",
        table_name="broker_connections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_broker_connections_tenant_id", table_name="broker_connections")
    op.drop_table("broker_connections")
    # ### end Alembic commands ###
