import { render } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import SymbolAvatar from '../../app/lib/shared/ui/SymbolAvatar';
import MANIFEST from '../../app/lib/shared/ui/logo-manifest.json';

/**
 * The company mark beside a ticker.
 *
 * Roughly forty F&O names have no usable logo, so the fallback is not an edge
 * case — it is on screen on every board. What is pinned here is that the
 * component decides from the manifest *before* rendering: reaching for the
 * image first and catching the failure costs a 404 per missing row and shows
 * the broken-image frame for a paint.
 */

const WITH_LOGO = Object.keys(MANIFEST)[0]!;
const WITH_LOGO_EXT = (MANIFEST as Record<string, string>)[WITH_LOGO]!;
const WITHOUT_LOGO = 'NOSUCHTICKER';

describe('SymbolAvatar', () => {
  it('draws the real mark when one is committed for the symbol', () => {
    const { container } = render(<SymbolAvatar symbol={WITH_LOGO} />);

    const img = container.querySelector('img')!;
    expect(img).toHaveAttribute('src', `/logos/${WITH_LOGO}.${WITH_LOGO_EXT}`);
    // Decorative: the ticker is always in the text beside it, so announcing
    // the logo too would read the row's name twice.
    expect(img).toHaveAttribute('alt', '');
  });

  it('falls back to initials without ever requesting a missing file', () => {
    const { container } = render(<SymbolAvatar symbol={WITHOUT_LOGO} />);

    expect(container.querySelector('img')).toBeNull();
    expect(container.textContent).toBe('NO');
  });

  it('keeps a symbol the same colour wherever it appears', () => {
    /* The hue is a handle the eye uses to find a row it already knows; it has
       to survive the symbol moving between boards. */
    const first = render(<SymbolAvatar symbol={WITHOUT_LOGO} />).container.querySelector('span')!;
    const second = render(<SymbolAvatar symbol={WITHOUT_LOGO} />).container.querySelector('span')!;

    expect(first.getAttribute('style')).toBe(second.getAttribute('style'));
  });

  it('matches the symbol regardless of how it is cased or spaced', () => {
    const { container } = render(<SymbolAvatar symbol={` ${WITH_LOGO.toLowerCase()} `} />);
    expect(container.querySelector('img')).toHaveAttribute(
      'src',
      `/logos/${WITH_LOGO}.${WITH_LOGO_EXT}`
    );
  });

  it('honours the size it is given, logo or initials', () => {
    const logo = render(<SymbolAvatar symbol={WITH_LOGO} size={40} />).container.querySelector(
      'img'
    )!;
    const fallback = render(
      <SymbolAvatar symbol={WITHOUT_LOGO} size={40} />
    ).container.querySelector('span')!;

    expect(logo).toHaveAttribute('width', '40');
    expect(fallback.getAttribute('style')).toContain('40px');
  });

  it('ships a manifest mapping each ticker to its file extension', () => {
    /* It is generated by the fetch script and imported at build time. A shape
       change there would surface as every avatar silently falling back to
       initials; a dropped extension would surface as broken images, because
       the server types the response from it. */
    const entries = Object.entries(MANIFEST as Record<string, string>);
    expect(entries.length).toBeGreaterThan(100);
    expect(entries.every(([symbol]) => symbol === symbol.toUpperCase())).toBe(true);
    expect(entries.every(([, ext]) => ext === 'png' || ext === 'svg')).toBe(true);
  });
});
