/**
 * Mirrors the response models in
 * `backend/src/marketcompass/contexts/identity/api/schemas.py`.
 *
 * Hand-written for now. Once `contracts/openapi/v1/openapi.yaml` is authored
 * these are generated by orval and this file goes away.
 */

export interface User {
  id: string;
  email: string;
  /** E.164 (`+919876543210`). Null for accounts created before it was collected. */
  phone: string | null;
  display_name: string;
  status: 'active' | 'pending_verification' | 'suspended' | 'deactivated';
  roles: readonly string[];
  email_verified: boolean;
  has_password: boolean;
  linked_providers: readonly string[];
  created_at: string;
  last_login_at: string | null;
}

export interface Tokens {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token: string;
  csrf_token: string;
}

export interface AuthenticationResult {
  user: User;
  tokens: Tokens;
  is_new_user: boolean;
}

export interface GoogleAuthorization {
  authorization_url: string;
  state: string;
}

export interface SessionSummary {
  id: string;
  created_at: string;
  expires_at: string;
  user_agent: string | null;
  ip_address: string | null;
  is_current: boolean;
}

/**
 * Error codes the auth endpoints can return. The UI branches on these rather
 * than on message text, which is free to change.
 */
export type AuthErrorCode =
  | 'invalid_credentials'
  | 'account_suspended'
  | 'account_disabled'
  | 'email_unverified'
  | 'email_taken'
  | 'phone_taken'
  | 'use_sso'
  | 'session_expired'
  | 'session_revoked'
  | 'registration_disabled'
  | 'rate_limited'
  | 'oauth_state_invalid'
  | 'oauth_failed'
  | 'domain_not_allowed'
  | 'validation_error';
